# data_paths.gd
# Shared data directory paths. Access via class_name (not an autoload).
# Both directories are generated by the YAML->tres pipeline under dev/tools/
# and are gitignored. Run the tres export tool on a fresh checkout before
# opening the project in Godot, or RegistryAudit will fail at boot.
class_name DataPaths
extends RefCounted

const COMMODITIES_DIR: String = "res://data/tres/commodities"
const CATEGORIES_DIR: String = "res://data/tres/categories"
const SUPER_CATEGORIES_DIR: String = "res://data/tres/super_categories"
const PERKS_DIR: String = "res://data/tres/perks"
const LOCATIONS_DIR: String = "res://data/tres/locations"
const LOTS_DIR: String = "res://data/tres/lots"
const CARS_DIR: String = "res://data/tres/cars"
const ANCHORS_DIR: String = "res://data/tres/anchors"
const CLUES_DIR: String = "res://data/tres/clues"
const ATTRIBUTES_DIR: String = "res://data/tres/attributes"
const AFFIXES_DIR: String = "res://data/tres/affixes"
const AFFIX_COMBINATIONS_DIR: String = "res://data/tres/affix_combinations"
