# data_paths.gd
# Shared data directory paths. Access via class_name (not an autoload).
class_name DataPaths
extends RefCounted

const ITEMS_DIR: String = "res://data/tres/items"
# Both directories are generated by the YAML→tres pipeline under dev/tools/
# and are gitignored. Run the tres export tool on a fresh checkout before
# opening the project in Godot, or RegistryAudit will fail at boot.
const CATEGORIES_DIR: String = "res://data/tres/categories"
const SUPER_CATEGORIES_DIR: String = "res://data/tres/super_categories"
const PERKS_DIR: String = "res://data/tres/perks"
const SKILLS_DIR: String = "res://data/tres/skills"
const LOCATIONS_DIR: String = "res://data/tres/locations"
const LOTS_DIR: String = "res://data/tres/lots"
const CARS_DIR: String = "res://data/tres/cars"
const MERCHANTS_DIR: String = "res://data/tres/merchants"
const SPECIAL_ORDERS_DIR: String = "res://data/tres/special_orders"
