# special_order.gd
# Runtime-only class representing an active special order for a merchant.
# Generated by MerchantRegistry._generate_order() from a SpecialOrderData template.
class_name SpecialOrder
extends RefCounted

var id: String # "{merchant_id}_{counter}"
var special_order_id: String # source SpecialOrderData.special_order_id
var merchant: MerchantData = null
var slots: Array[OrderSlot] = []
var buff: float = 1.0
var completion_bonus: int = 0
var deadline_day: int = 0 # absolute day

var allow_partial_delivery: bool = false

enum Eligibility {
    NONE,
    PARTIAL,
    FULL,
}


static func create(
        template: SpecialOrderData,
        new_merchant: MerchantData,
        order_id: String,
) -> SpecialOrder:
    var order := SpecialOrder.new()
    order.id = order_id
    order.special_order_id = template.special_order_id
    order.merchant = new_merchant
    order.buff = randf_range(template.buff_min, template.buff_max)
    order.completion_bonus = template.completion_bonus
    order.deadline_day = SaveManager.current_day + template.deadline_days
    order.allow_partial_delivery = template.allow_partial_delivery

    var slot_count: int = randi_range(template.slot_count_min, template.slot_count_max)
    for i in range(slot_count):
        var pool_entry: SpecialOrderSlotPoolEntry = template.slot_pool.pick_random()
        order.slots.append(OrderSlot.create(pool_entry))

    return order


func is_complete() -> bool:
    for slot: OrderSlot in slots:
        if not slot.is_full():
            return false
    return true


func is_expired(current_day: int) -> bool:
    return current_day > deadline_day


func check_eligibility(storage: Array) -> Eligibility:
    var pool: Array = storage.duplicate()
    var has_incomplete: bool = false
    var all_full: bool = true
    var any_match: bool = false

    for slot: OrderSlot in slots:
        var result: Dictionary = slot.check_eligibility(pool)
        for entry: Variant in result["matches"]:
            pool.erase(entry)

        if slot.remaining() == 0:
            continue

        has_incomplete = true
        if result["eligibility"] == Eligibility.FULL:
            any_match = true
        elif result["eligibility"] == Eligibility.PARTIAL:
            all_full = false
            any_match = true
        else:
            all_full = false

    if not has_incomplete:
        return Eligibility.FULL
    if all_full and any_match:
        return Eligibility.FULL
    if any_match:
        return Eligibility.PARTIAL
    return Eligibility.NONE


func to_dict() -> Dictionary:
    var slot_dicts: Array = []
    for slot: OrderSlot in slots:
        slot_dicts.append(slot.to_dict())
    return {
        "id": id,
        "special_order_id": special_order_id,
        "merchant_id": merchant.merchant_id if merchant else "",
        "slots": slot_dicts,
        "buff": buff,
        "completion_bonus": completion_bonus,
        "deadline_day": deadline_day,
        "allow_partial_delivery": allow_partial_delivery,
    }


static func from_dict(d: Dictionary) -> SpecialOrder:
    var order := SpecialOrder.new()
    order.id = str(d.get("id", ""))
    order.special_order_id = str(d.get("special_order_id", ""))
    order.merchant = MerchantRegistry.get_merchant_by_id(str(d.get("merchant_id", "")))
    order.buff = float(d.get("buff", 1.0))
    order.completion_bonus = int(d.get("completion_bonus", 0))
    order.deadline_day = int(d.get("deadline_day", 0))
    order.allow_partial_delivery = bool(d.get("allow_partial_delivery", false))

    var raw_slots: Array = d.get("slots", [])
    for sd: Variant in raw_slots:
        if sd is Dictionary:
            order.slots.append(OrderSlot.from_dict(sd))
    return order
