# tutorial_events.gd
# StringName constants for semantic tutorial events.
# Gameplay systems emit these; the flow layer subscribes.
class_name TutorialEvents

const LOCATION_SELECTED: StringName = &"location_selected"
const LOT_SELECTED: StringName = &"lot_selected"
const INSPECTION_PERFORMED: StringName = &"inspection_performed"
const INSPECTION_ITEM_SELECTED: StringName = &"inspection_item_selected"
const INSPECTION_ITEM_UNVEILED: StringName = &"inspection_item_unveiled"
const INSPECTION_REVIEW_OPENED: StringName = &"inspection_review_opened"
const INSPECTION_AUCTION_STARTED: StringName = &"inspection_auction_started"
const AUCTION_WON: StringName = &"auction_won"
const CARGO_ITEM_SELECTED: StringName = &"cargo_item_selected"
const CARGO_ITEM_PLACED: StringName = &"cargo_item_placed"
const CARGO_CONTINUE_REQUESTED: StringName = &"cargo_continue_requested"
const CARGO_LOADED: StringName = &"cargo_loaded"
const RUN_REVIEWED: StringName = &"run_reviewed"
const SALE_COMPLETED: StringName = &"sale_completed"
const STORAGE_CONDITION_IMPROVED: StringName = &"storage_condition_improved"
const STORAGE_RESEARCH_PERFORMED: StringName = &"storage_research_performed"
const ACTIVITY_CHOSEN: StringName = &"activity_chosen"
const CHOOSER_OPENED: StringName = &"chooser_opened"
const AUCTION_RESOLVED: StringName = &"auction_resolved"
const BID_PLACED: StringName = &"bid_placed"
const DAY_SUMMARY_CONTINUED: StringName = &"day_summary_continued"
const REVEAL_COMPLETED: StringName = &"reveal_completed"
const REVEAL_CONTINUED: StringName = &"reveal_continued"
const CARGO_OPENED: StringName = &"cargo_opened"
const SELL_AGGRESSIVE_REQUESTED: StringName = &"sell_aggressive_requested"
const SELL_ITEM_PLACED: StringName = &"sell_item_placed"
const DICE_TOGGLED: StringName = &"dice_toggled"
