locales:
  - id: en
    fallbacks: []
    label: English
  - id: zh_TW
    fallbacks: [zh_CN, en]
    label: 繁體中文
  - id: zh_CN
    fallbacks: [zh_TW, en]
    label: 简体中文
blocks:
  - ui
  - tutorial
  - items
  - clues
  - locations
  - affixes
  - categories
  - commodities
  - perks
  - system
