extends Node

@export var scenes: SceneRegistry

# One ItemEntry per item in the current lot.
# Generated by the warehouse entry scene; persists through the full run.
var item_entries: Array[ItemEntry] = []

# Properties of this lot as a whole.
# Generated by the warehouse entry scene; relevant through the end of auction.
var lot_data: LotData = null

# Written by Block 04 (Auction).
# { "paid_price": int, "won_items": Array[ItemEntry] }
# paid_price = 0 and won_items = [] when the player passes or loses.
var lot_result: Dictionary = { }

# Written by Block 05 (Cargo Loading).
# The subset of won_items the player chose to bring home.
var cargo_items: Array[ItemEntry] = []

# Written by Block 05 (Cargo Loading) and Block 06 (Home Appraisal).
# { "onsite_proceeds": int, "sell_value": int, "paid_price": int, "net": int }
var run_result: Dictionary = { }

# Written by Block 05 (Cargo Loading). The total amount earned by selling items onsite instead of taking them home.
var onsite_proceeds: int = 0

# ── Scene transitions ─────────────────────────────────────────────────────────


func go_to_warehouse_entry() -> void:
    get_tree().change_scene_to_packed(scenes.warehouse_entry)


func go_to_inspection() -> void:
    get_tree().change_scene_to_packed(scenes.inspection)


func go_to_auction() -> void:
    get_tree().change_scene_to_packed(scenes.auction)


func go_to_cargo() -> void:
    get_tree().change_scene_to_packed(scenes.cargo)


func go_to_appraisal() -> void:
    get_tree().change_scene_to_packed(scenes.appraisal)
