# special_order.gd
# Runtime-only class representing an active special order for a merchant.
# Generated by MerchantRegistry._generate_order() from a SpecialOrderData template.
class_name SpecialOrder
extends RefCounted

# Accepted pricing_mode strings. Each maps to a PriceConfig preset in
# _rebuild_pricing_config().
const PRICING_MODE_FLAT := "flat"
const PRICING_MODE_CONDITION := "condition"
const PRICING_MODE_APPRAISED := "appraised"
const PRICING_MODE_MARKET := "market"

var id: String # "{merchant_id}_{counter}"
var special_order_id: String # source SpecialOrderData.special_order_id
var merchant_id: String
var slots: Array[OrderSlot] = []
var buff: float = 1.0
var completion_bonus: int = 0
var deadline_day: int = 0 # absolute day

# Pricing preset copied from the template. Source of truth for the runtime
# PriceConfig; the individual bools below are derived from this.
var pricing_mode: String = PRICING_MODE_FLAT

# Per-factor pricing flags persisted with the order. The runtime PriceConfig
# below is rebuilt from pricing_mode in create() and from_dict(). Persisted
# alongside pricing_mode for debugging and backward compatibility.
var uses_condition: bool = false
var uses_knowledge: bool = false
var uses_market: bool = false

var allow_partial_delivery: bool = false

# PriceConfig assembled once from pricing_mode plus buff; reused for every
# item in compute_item_price() so per-row rendering never allocates.
var pricing_config: PriceConfig = null

enum Eligibility {
    NONE,
    PARTIAL,
    FULL,
}


static func create(
        template: SpecialOrderData,
        new_merchant_id: String,
        order_id: String,
) -> SpecialOrder:
    var order := SpecialOrder.new()
    order.id = order_id
    order.special_order_id = template.special_order_id
    order.merchant_id = new_merchant_id
    order.buff = randf_range(template.buff_min, template.buff_max)
    order.completion_bonus = template.completion_bonus
    order.deadline_day = SaveManager.current_day + template.deadline_days
    order.pricing_mode = template.pricing_mode
    order.allow_partial_delivery = template.allow_partial_delivery
    order._rebuild_pricing_config()

    var slot_count: int = randi_range(template.slot_count_min, template.slot_count_max)
    for i in range(slot_count):
        var pool_entry: SpecialOrderSlotData = template.slot_pool.pick_random()
        order.slots.append(OrderSlot.create(pool_entry))

    return order


func _rebuild_pricing_config() -> void:
    pricing_config = _config_for_mode(pricing_mode)
    pricing_config.multiplier = buff
    uses_condition = pricing_config.condition
    uses_knowledge = pricing_config.knowledge
    uses_market = pricing_config.market


static func _config_for_mode(mode: String) -> PriceConfig:
    match mode:
        PRICING_MODE_FLAT:
            return PriceConfig.plain()
        PRICING_MODE_CONDITION:
            return PriceConfig.with_condition()
        PRICING_MODE_APPRAISED:
            return PriceConfig.with_appraisal()
        PRICING_MODE_MARKET:
            return PriceConfig.with_market()
        _:
            push_warning("Unknown pricing_mode '%s'; falling back to flat" % mode)
            return PriceConfig.plain()


func is_complete() -> bool:
    for slot: OrderSlot in slots:
        if not slot.is_full():
            return false
    return true


func is_expired(current_day: int) -> bool:
    return current_day > deadline_day


func check_eligibility(storage: Array) -> Eligibility:
    var pool: Array = storage.duplicate()
    var has_incomplete: bool = false
    var all_full: bool = true
    var any_match: bool = false

    for slot: OrderSlot in slots:
        var result: Dictionary = slot.check_eligibility(pool)
        for entry: Variant in result["matches"]:
            pool.erase(entry)

        if slot.remaining() == 0:
            continue

        has_incomplete = true
        if result["eligibility"] == Eligibility.FULL:
            any_match = true
        elif result["eligibility"] == Eligibility.PARTIAL:
            all_full = false
            any_match = true
        else:
            all_full = false

    if not has_incomplete:
        return Eligibility.FULL
    if all_full and any_match:
        return Eligibility.FULL
    if any_match:
        return Eligibility.PARTIAL
    return Eligibility.NONE


func compute_item_price(entry: ItemEntry) -> int:
    return entry.compute_price(pricing_config)


func to_dict() -> Dictionary:
    var slot_dicts: Array = []
    for slot: OrderSlot in slots:
        slot_dicts.append(slot.to_dict())
    return {
        "id": id,
        "special_order_id": special_order_id,
        "merchant_id": merchant_id,
        "slots": slot_dicts,
        "buff": buff,
        "completion_bonus": completion_bonus,
        "deadline_day": deadline_day,
        "pricing_mode": pricing_mode,
        "uses_condition": uses_condition,
        "uses_knowledge": uses_knowledge,
        "uses_market": uses_market,
        "allow_partial_delivery": allow_partial_delivery,
    }


static func from_dict(d: Dictionary) -> SpecialOrder:
    var order := SpecialOrder.new()
    order.id = str(d.get("id", ""))
    order.special_order_id = str(d.get("special_order_id", ""))
    order.merchant_id = str(d.get("merchant_id", ""))
    order.buff = float(d.get("buff", 1.0))
    order.completion_bonus = int(d.get("completion_bonus", 0))
    order.deadline_day = int(d.get("deadline_day", 0))

    # New saves persist pricing_mode. Old saves persisted uses_condition_pricing
    # only — fall back to condition mode if it was true, flat otherwise.
    if d.has("pricing_mode"):
        order.pricing_mode = str(d["pricing_mode"])
    elif bool(d.get("uses_condition_pricing", false)):
        order.pricing_mode = PRICING_MODE_CONDITION
    else:
        order.pricing_mode = PRICING_MODE_FLAT

    order.allow_partial_delivery = bool(d.get("allow_partial_delivery", false))
    order._rebuild_pricing_config()

    var raw_slots: Array = d.get("slots", [])
    for sd: Variant in raw_slots:
        if sd is Dictionary:
            order.slots.append(OrderSlot.from_dict(sd))
    return order
