# special_order.gd
# Runtime-only class representing an active special order for a merchant.
# Generated by MerchantRegistry._generate_order() from a SpecialOrderData template.
class_name SpecialOrder
extends RefCounted

var id: String # "{merchant_id}_{counter}"
var special_order_id: String # source SpecialOrderData.special_order_id
var merchant_id: String
var slots: Array[OrderSlot] = []
var buff: float = 1.0
var completion_bonus: int = 0
var deadline_day: int = 0 # absolute day
var uses_condition_pricing: bool = false
var allow_partial_delivery: bool = false

enum Eligibility {
    NONE,
    PARTIAL,
    FULL,
}


static func create(
        template: SpecialOrderData,
        merchant_id: String,
        order_id: String,
) -> SpecialOrder:
    var order := SpecialOrder.new()
    order.id = order_id
    order.special_order_id = template.special_order_id
    order.merchant_id = merchant_id
    order.buff = randf_range(template.buff_min, template.buff_max)
    order.completion_bonus = template.completion_bonus
    order.deadline_day = SaveManager.current_day + template.deadline_days
    order.uses_condition_pricing = template.uses_condition_pricing
    order.allow_partial_delivery = template.allow_partial_delivery

    var slot_count: int = randi_range(template.slot_count_min, template.slot_count_max)
    for i in range(slot_count):
        order.slots.append(OrderSlot.create(template))

    return order


func is_complete() -> bool:
    for slot: OrderSlot in slots:
        if not slot.is_full():
            return false
    return true


func is_expired(current_day: int) -> bool:
    return current_day > deadline_day


func check_eligibility(storage: Array) -> Eligibility:
    var available: Array = storage.duplicate()
    var all_satisfiable: bool = true
    var any_satisfiable: bool = false

    for slot: OrderSlot in slots:
        var needed: int = slot.remaining()
        if needed <= 0:
            continue

        var matched: int = 0
        var consumed: Array = []
        for entry: Variant in available:
            if slot.accepts(entry as ItemEntry):
                consumed.append(entry)
                matched += 1
                if matched >= needed:
                    break

        for item: Variant in consumed:
            available.erase(item)

        if matched <= 0:
            all_satisfiable = false
        elif matched < needed:
            all_satisfiable = false
            any_satisfiable = true
        else:
            any_satisfiable = true

    if all_satisfiable and any_satisfiable:
        return Eligibility.FULL
    elif any_satisfiable:
        return Eligibility.PARTIAL
    else:
        # All slots already full (order complete) counts as FULL.
        for slot: OrderSlot in slots:
            if slot.remaining() > 0:
                return Eligibility.NONE
        return Eligibility.FULL


func compute_item_price(entry: ItemEntry) -> int:
    var base: int = entry.active_layer().base_value
    if uses_condition_pricing:
        return int(base * entry.get_condition_multiplier() * buff)
    else:
        return int(base * buff)


func to_dict() -> Dictionary:
    var slot_dicts: Array = []
    for slot: OrderSlot in slots:
        slot_dicts.append(slot.to_dict())
    return {
        "id": id,
        "special_order_id": special_order_id,
        "merchant_id": merchant_id,
        "slots": slot_dicts,
        "buff": buff,
        "completion_bonus": completion_bonus,
        "deadline_day": deadline_day,
        "uses_condition_pricing": uses_condition_pricing,
        "allow_partial_delivery": allow_partial_delivery,
    }


static func from_dict(d: Dictionary) -> SpecialOrder:
    var order := SpecialOrder.new()
    order.id = str(d.get("id", ""))
    order.special_order_id = str(d.get("special_order_id", ""))
    order.merchant_id = str(d.get("merchant_id", ""))
    order.buff = float(d.get("buff", 1.0))
    order.completion_bonus = int(d.get("completion_bonus", 0))
    order.deadline_day = int(d.get("deadline_day", 0))
    order.uses_condition_pricing = bool(d.get("uses_condition_pricing", false))
    order.allow_partial_delivery = bool(d.get("allow_partial_delivery", false))
    var raw_slots: Array = d.get("slots", [])
    for sd: Variant in raw_slots:
        if sd is Dictionary:
            order.slots.append(OrderSlot.from_dict(sd))
    return order
