# lot_data.gd
# Properties of the lot as a whole for a single run.
# Generated by the warehouse entry scene; relevant through the end of auction.
class_name LotData
extends Resource

# ── State ─────────────────────────────────────────────────────────────────────

# Scales NPC bidding aggression in Block 04. MVP: fixed at 1.0.
@export var aggressive_factor: float = 1.0

# Post Demo only; placeholder field, ignored for now.
@export var knowledge_factor: float = 1.0
